kind: Cluster
name: kind
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
- role: control-plane
  extraPortMappings:
  - containerPort: 30080
    hostPort: 30080
  - containerPort: 30081
    hostPort: 30081
  extraMounts:
  - hostPath: /prometheus
    containerPath: /prometheus
    propagation: HostToContainer
  - hostPath: /grafana
    containerPath: /grafana
    propagation: HostToContainer
containerdConfigPatches:
- |-
  [plugins."io.containerd.grpc.v1.cri".registry.mirrors."localhost:5000"]
    endpoint = ["http://kind-registry:5000"]
