# For use with FB Docker and STDOUT tail
[SERVICE]
    Flush               1
    Daemon              Off
    Log_Level           info
    HTTP_Server         On
    HTTP_Listen         0.0.0.0
    HTTP_Port           2020
    Parsers_File        parsers.conf
    storage.path        /var/log/flb-storage/
    storage.sync        normal
    storage.backlog.mem_limit 32MB
[INPUT]
    Name                tail
    Tag                 docker.*
    Path                /var/lib/docker/containers/*/*-json.log
    # Important exclusion!
    Exclude_Path        /var/lib/docker/containers/${HOSTNAME}*
    multiline.parser    docker, cri
    DB                  /var/log/flb_docker.db
    Key                 fbcd
    Ignore_Older        2m
    Mem_Buf_Limit       32MB
    Skip_Long_Lines     Off
    Skip_Empty_Lines    Off
    Refresh_Interval    10
    storage.type        filesystem
[FILTER]
    Name                parser
    Match               *
    Parser              json
    Key_Name            log
    Reserve_Data        On
[FILTER]
    Name    modify
    Match   docker.*
    Add     k_app       ngsa-memory
    Add     kubernetes_container_name ngsa-${HOSTNAME}
[OUTPUT]
    Name                stdout
    match               docker.*
# Output to Log Analytics
# [OUTPUT]
#     Name                azure
#     Match               docker.var.lib.docker.containers.*
#     Customer_ID         ${WORKSPACE_ID}
#     Shared_Key          ${SHARED_KEY}
#     Log_Type            ngsa
#     storage.total_limit_size  15M
