# Overall Settings
[SERVICE]
    Flush               1
    Daemon              Off
    Log_Level           info
    HTTP_Server         On
    Parsers_File        parsers.conf
    HTTP_Listen         0.0.0.0
    HTTP_Port           2020
    storage.path        /var/tmp/log/flb-storage/
    storage.sync        normal
    storage.backlog.mem_limit 32MB

# Input logs
[INPUT]
    Name                tail
    Tag                 docker.*
    Path                /path/to/log/output.log
    # Path                /var/lib/docker/containers/*/*-json.log
    multiline.parser    docker
    DB                  /var/tmp/log/flb_docker.db
    Ignore_Older        2m
    Mem_Buf_Limit       32MB
    Skip_Long_Lines     Off
    Skip_Empty_Lines    On
    Refresh_Interval    10
    storage.type        filesystem

# Modification via filter
[FILTER]
    Name                parser
    Match               *
    # Since this is baremetal, default json parser is not available directly 
    Parser              simple-json 
    Key_Name            log
    Reserve_Data        On

# Output
[OUTPUT]
    Name                stdout
    match               docker.*
# Output to Log Analytics
# [OUTPUT]
#     Name                stdout
#     match               docker.*
#     Name                azure
#     Match               docker.var.lib.docker.containers.*
#     Customer_ID         ${WORKSPACE_ID}
#     Shared_Key          ${SHARED_KEY}
#     Log_Type            ${NGSA_LOG}
#     storage.total_limit_size  15M
