---
apiVersion: v1
kind: ConfigMap
metadata:
  name: fluentbit
data:
  fluent-bit.conf: |
    [SERVICE]
       Flush 1
       Daemon Off
       Log_Level trace
       Parsers_File parsers.conf
       HTTP_Server On
       HTTP_Listen   0.0.0.0
       HTTP_Port     2020
       storage.path  /var/log/flb-storage/
       storage.sync  normal
       storage.backlog.mem_limit 32MB
    @INCLUDE input.conf
    @INCLUDE output.conf
  input.conf: |
    [INPUT]
       Name tail
       Path /var/log/containers/*istio-proxy*.log
       Parser cri
       Tag kube.*
       Mem_Buf_Limit 5MB
  output.conf: |
    [OUTPUT]
       name loki
       match *
       host loki.tracing.svc
       port 3100
       tenant_id ""
       labels job=fluentbit
       label_keys $trace_id
       auto_kubernetes_labels on
  parsers.conf: |
    [PARSER]
       Name cri
       Format regex
       Regex ^(?<time>[^ ]+) (?<stream>stdout|stderr) (?<logtag>[^ ]*) (?<message>.*)$
       Time_Key    time
       Time_Format %Y-%m-%dT%H:%M:%S.%L%z

