---
spec:
  template:
    spec:
      containers:
      - name: istio-proxy
        volumeMounts:
        - mountPath: "/var/local/lib/wasm-filters"
          name: wasmfilters-dir
      volumes:
      - configMap:
          name: burst-wasm-filter
        name: wasmfilters-dir
