##################################################################################################
# Details service
##################################################################################################
apiVersion: v1
kind: Service
metadata:
  name: pymetric
  labels:
    app: pymetric
    service: pymetric
spec:
  ports:
  - port: 32888 
    name: http
  selector:
    app: pymetric
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: pymetric
  labels:
    account: pymetric
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pymetric
  labels:
    app: pymetric
    version: v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pymetric
      version: v1
  template:
    metadata:
      labels:
        app: pymetric
        version: v1
    spec:
      serviceAccountName: pymetric
      containers:
      - name: pymetric
        image: localhost:5000/pymetric:local
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 32888 
        securityContext:
          runAsUser: 1000
