apiVersion: v1
kind: Service
metadata:
  name: kialiservice
  namespace: istio-system
spec:
  selector: 
    app: kiali
  type: NodePort  
  ports:
    - port: 20001
      targetPort: 20001 
      nodePort: 30089