##################################################################################################
# Details service
##################################################################################################
kind: Namespace
apiVersion: v1
metadata:
  name: burstservice
---
apiVersion: v1
kind: Service
metadata:
  name: burst
  namespace: burstservice
  labels:
    app: burst
    service: burst
spec:
  ports:
  - port: 8080 
    name: http
    nodePort: 30081
  type: NodePort # For external access (k3d, kind)
  selector:
    app: burst
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: burst
  namespace: burstservice
  labels:
    account: burst
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: burst-role
  namespace: burstservice
rules:
- apiGroups:
  - autoscaling
  resources:
  - "*"
  verbs:
  - list
  - get
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  namespace: burstservice
  name: burst-rolebind
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: burst-role
subjects:
- kind: ServiceAccount
  name: burst
  namespace: burstservice
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: burst
  namespace: burstservice
  labels:
    app: burst
    version: v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: burst
      version: v1
  template:
    metadata:
      labels:
        app: burst
        version: v1
    spec:
      serviceAccountName: burst
      containers:
      - name: burst
        image: k3d-registry.localhost:5000/burst:local
        imagePullPolicy: Always
        ports:
        - containerPort: 8080 
        securityContext:
          runAsUser: 1000
